
const PRODUCTS=[{"id": "01", "name": "Asteria 80 Refractor Telescope", "category": "Beginner Telescopes", "description": "A clean 80 mm refractor for relaxed lunar and planetary sessions.", "price": 189}, {"id": "02", "name": "Luna 8 Dobsonian Telescope", "category": "Deep Sky", "description": "A classic reflector for bright deep-sky targets.", "price": 329}, {"id": "03", "name": "Noctis Astronomy Binoculars", "category": "Binoculars", "description": "Wide-field optics for scanning constellations and star clusters.", "price": 159}, {"id": "04", "name": "Orbit Pro Eyepiece Set", "category": "Eyepieces", "description": "A versatile collection for changing magnification during a session.", "price": 119}, {"id": "05", "name": "Celestial Planisphere", "category": "Star Maps", "description": "A rotating sky guide for planning observations before sunset.", "price": 49}, {"id": "06", "name": "Equinox Tracking Mount", "category": "Mounts", "description": "A compact equatorial-style mount for steadier tracking.", "price": 219}, {"id": "07", "name": "Redline Dark-Adapted Torch", "category": "Observation Gear", "description": "Low-glare red illumination for preserving night vision.", "price": 34}, {"id": "08", "name": "Atlas Telescope Carry Case", "category": "Cases", "description": "Protective padded storage for portable optical equipment.", "price": 89}, {"id": "09", "name": "Lunar Filter Collection", "category": "Filters", "description": "A small set of visual filters for brighter lunar and planetary targets.", "price": 39}, {"id": "10", "name": "Orbita Celestial Globe", "category": "Education", "description": "A desk-ready globe for exploring constellations and celestial coordinates.", "price": 129}, {"id": "11", "name": "Field Observer Journal", "category": "Observation Tools", "description": "A guided notebook for recording objects, conditions and sessions.", "price": 24}, {"id": "12", "name": "Asteria Field Telescope", "category": "Travel Telescopes", "description": "A compact refractor setup designed for easy transport to dark skies.", "price": 209}];
const money=n=>"$"+n.toFixed(2);
const state={cart:JSON.parse(localStorage.getItem("orbita-cart")||"[]"),saved:JSON.parse(localStorage.getItem("orbita-saved")||"[]")};
function saveState(){localStorage.setItem("orbita-cart",JSON.stringify(state.cart));localStorage.setItem("orbita-saved",JSON.stringify(state.saved));}
function productById(id){return PRODUCTS.find(p=>p.id===id)||PRODUCTS[0]}
function cartCount(){return state.cart.reduce((a,x)=>a+x.qty,0)}
function renderHeader(){const el=document.querySelector("[data-cart-count]");if(el)el.textContent=cartCount()}
function addToCart(id){const item=state.cart.find(x=>x.id===id);item?item.qty++:state.cart.push({id,qty:1});saveState();renderHeader();toast("Added to your observation kit.")}
function toggleSaved(id){const i=state.saved.indexOf(id);i>=0?state.saved.splice(i,1):state.saved.push(id);saveState();toast(i>=0?"Removed from saved items.":"Saved for later.")}
function toast(msg){let t=document.querySelector(".toast");if(!t){t=document.createElement("div");t.className="toast";document.body.appendChild(t)}t.textContent=msg;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),1800)}
function productCard(p){return `<article class="card"><a href="product.html?id=${p.id}"><div class="card-media"><img src="assets/products/product-${p.id}.webp" alt="${p.name}"></div></a><div class="card-body"><div class="tag">${p.category}</div><h3>${p.name}</h3><p class="muted">${p.description}</p><div class="price">${money(p.price)}</div><div class="actions"><button class="btn primary" onclick="addToCart('${p.id}')">Add to kit</button><button class="btn" onclick="toggleSaved('${p.id}')">Save</button></div></div></article>`}
function renderProducts(list=PRODUCTS){const el=document.querySelector("[data-products]");if(el)el.innerHTML=list.map(productCard).join("")}
function initCatalog(){const input=document.querySelector("[data-search]"),cat=document.querySelector("[data-category]");const run=()=>{const q=(input?.value||"").toLowerCase(),c=cat?.value||"";renderProducts(PRODUCTS.filter(p=>(!q||(p.name+" "+p.category+" "+p.description).toLowerCase().includes(q))&&(!c||p.category===c)))};input?.addEventListener("input",run);cat?.addEventListener("change",run);renderProducts()}
function initProduct(){const id=new URLSearchParams(location.search).get("id")||"01",p=productById(id),el=document.querySelector("[data-product]");if(!el)return;el.innerHTML=`<div><img src="assets/products/product-${p.id}.webp" alt="${p.name}"></div><div><div class="tag">${p.category}</div><h1>${p.name}</h1><p class="lede">${p.description}</p><div class="price" style="font-size:30px">${money(p.price)}</div><div class="specs"><div class="spec"><b>Designed for</b><span>Night-sky observation</span></div><div class="spec"><b>Availability</b><span>Ready to explore</span></div><div class="spec"><b>Store concept</b><span>ORBITA Astronomy</span></div><div class="spec"><b>Shipping</b><span>See shipping page</span></div></div><div class="actions"><button class="btn primary" onclick="addToCart('${p.id}')">Add to observation kit</button><button class="btn" onclick="toggleSaved('${p.id}')">Save item</button></div></div>`}
function initCart(){const el=document.querySelector("[data-cart]");if(!el)return;const rows=state.cart.map(x=>{const p=productById(x.id);return `<div class="card" style="display:grid;grid-template-columns:140px 1fr"><img src="assets/products/product-${p.id}.webp" alt="${p.name}" style="width:140px;height:140px;object-fit:cover"><div class="card-body"><h3>${p.name}</h3><p class="muted">Quantity: ${x.qty}</p><div class="price">${money(p.price*x.qty)}</div></div></div>`}).join("");const total=state.cart.reduce((a,x)=>a+productById(x.id).price*x.qty,0);el.innerHTML=rows||"<div class=\"notice\">Your observation kit is empty. Start with the night sky.</div>";const t=document.querySelector("[data-total]");if(t)t.textContent=money(total)}
document.addEventListener("DOMContentLoaded",()=>{renderHeader();initCatalog();initProduct();initCart()});
